# Generated by Django 5.0.1 on 2024-02-13 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classattendance',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attended_class_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classattendance',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_class_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort', to='users.cohort'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classattendance',
            name='class_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.classschedule'),
        ),
        migrations.AddField(
            model_name='query',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='query',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='query',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='querycomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_query_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='querycomment',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.query'),
        ),
    ]
